/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AccountStatus = { 'Active' : null } |
  { 'Suspended' : null };
export type AllocateShortResult = { 'ok' : { 'unitsOpened' : number } } |
  { 'err' : string };
export interface AssetPrice {
  'currentAllocated' : number,
  'name' : string,
  'baseScore' : number,
  'redeemPrice' : number,
  'buyPrice' : number,
  'category' : string,
  'maxAllocation' : number,
  'volatilityBuffer' : number,
}
export interface Cell { 'value' : Value, 'name' : string }
export interface CircuitBreakerStatus {
  'velocity' : number,
  'breakerActive' : boolean,
}
export interface FullPositionView {
  'shortUnits' : number,
  'longUnits' : number,
  'shortEntryScore' : number,
  'longEntryScore' : number,
  'shortMarkToMarketValue' : number,
  'longMarkToMarketValue' : number,
}
export interface Holding {
  'allocationTimestamp' : bigint,
  'accruedYield' : number,
  'units' : number,
  'assetName' : string,
  'yieldStartTime' : bigint,
}
export interface HttpHeader { 'value' : string, 'name' : string }
export interface HttpResponse {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export interface NewsEvent {
  'sentimentScore' : number,
  'headline' : string,
  'category' : NewsEventCategory,
  'relatedIndex' : [] | [string],
}
export type NewsEventCategory = { 'AI' : null } |
  { 'Mexico' : null } |
  { 'Washington' : null } |
  { 'Warriors' : null };
export interface ProcessedHeadline {
  'impact' : number,
  'sentimentLabel' : string,
  'text' : string,
  'targetIndex' : string,
  'sourceTier' : bigint,
  'timestamp' : bigint,
  'confidence' : number,
}
export type RedeemShortResult = { 'ok' : { 'valueCredited' : number } } |
  { 'err' : string };
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export interface ShortPositionView {
  'shortUnits' : number,
  'shortEntryScore' : number,
  'markToMarketValue' : number,
}
export type SubsidyReserveEntry = [string, number];
export type SubsidyReserveMap = Array<SubsidyReserveEntry>;
export interface TickRecord {
  'topHeadline' : [] | [string],
  'tickIndex' : bigint,
  'scores' : Array<[string, number]>,
  'gsiValue' : number,
  'timestamp' : bigint,
}
export interface Transaction {
  'id' : bigint,
  'transactionType' : TransactionType,
  'username' : string,
  'timestamp' : bigint,
  'units' : [] | [number],
  'assetName' : [] | [string],
  'amount' : number,
  'assetInvolved' : [] | [string],
  'dollarAmount' : [] | [number],
}
export type TransactionType = { 'buy' : null } |
  { 'sell' : null } |
  { 'deposit' : null } |
  { 'shortAllocate' : null } |
  { 'redeemAll' : null } |
  { 'withdrawal' : null } |
  { 'shortRedeem' : null };
export interface TransformArgs {
  'context' : Uint8Array,
  'response' : HttpResponse,
}
export type TrendDirection = { 'up' : null } |
  { 'down' : null };
export interface TrendState {
  'direction' : TrendDirection,
  'remainingDuration' : bigint,
  'stepSize' : number,
}
export interface UserProfile { 'username' : string, 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'adjustUserBalance' : ActorMethod<[string, number], undefined>,
  'allocateFunds' : ActorMethod<[string, number], boolean>,
  'allocateShort' : ActorMethod<[string, number], AllocateShortResult>,
  /**
   * / Legacy function retained for backward compatibility.
   * / New callers should use classifyHeadline() instead.
   */
  'analyzeSentiment' : ActorMethod<[string], string>,
  'applyNewsEvent' : ActorMethod<[NewsEvent], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'backfillVolume' : ActorMethod<[], undefined>,
  /**
   * / Public update function — frontend calls this to classify a headline.
   * / HTTP outcalls require update calls (not query).
   * / Returns neutral_fallback if key is not set or on any error.
   * / NOTE: field is "sentimentLabel" not "label" — "label" is a reserved keyword in Motoko.
   */
  'classifyHeadline' : ActorMethod<
    [string],
    { 'sentimentLabel' : string, 'source' : string, 'confidence' : number }
  >,
  'depositFunds' : ActorMethod<[number], undefined>,
  'execute' : ActorMethod<[string], Result>,
  'fetchACLUData' : ActorMethod<[], string>,
  'fetchBLSData' : ActorMethod<[], string>,
  'fetchCongressData' : ActorMethod<[], string>,
  'fetchCongressTraditionalData' : ActorMethod<[], string>,
  'fetchCourtListenerData' : ActorMethod<[], string>,
  'fetchEPAData' : ActorMethod<[], string>,
  'fetchFTCData' : ActorMethod<[], string>,
  'fetchFedData' : ActorMethod<[], string>,
  'fetchGDELTData' : ActorMethod<[], string>,
  'fetchGlobeNewswire' : ActorMethod<[], string>,
  'fetchNews' : ActorMethod<[], string>,
  'fetchOMDBDCData' : ActorMethod<[], string>,
  'fetchOMDBMarvelData' : ActorMethod<[], string>,
  'fetchRedditFeed' : ActorMethod<[string], string>,
  'fetchReliefWebData' : ActorMethod<[], string>,
  'fetchSCOTUSData' : ActorMethod<[], string>,
  'fetchSECFilings' : ActorMethod<[], string>,
  'fetchTMDBData' : ActorMethod<[], string>,
  'fetchTMDBPopularData' : ActorMethod<[], string>,
  'fetchUSPTOData' : ActorMethod<[], string>,
  'fetchYouTubeData' : ActorMethod<[], string>,
  'getAllHoldings' : ActorMethod<[], Array<[string, Holding]>>,
  'getAllUsers' : ActorMethod<
    [],
    Array<[string, number, number, number, AccountStatus]>
  >,
  'getAssetPrices' : ActorMethod<[], Array<AssetPrice>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCircuitBreakerStatus' : ActorMethod<[string], CircuitBreakerStatus>,
  'getCurrentTrends' : ActorMethod<[], Array<[string, TrendState]>>,
  /**
   * / Returns the current cycles balance of this canister.
   * / PUBLIC — no auth required. Use for monitoring without controller access:
   * /   dfx canister call noek7-3yaaa-aaaaj-qn6ea-cai getCyclesBalance --network ic
   */
  'getCyclesBalance' : ActorMethod<[], bigint>,
  /**
   * / Returns Finnhub key status without exposing the value. Open during pre-deployment — any signed-in caller may check the key.
   */
  'getFinnhubKeyStatus' : ActorMethod<[], string>,
  'getHoldings' : ActorMethod<[string], [] | [Holding]>,
  /**
   * / Returns key status without exposing the value. Open during pre-deployment — any signed-in caller may check the key.
   */
  'getHuggingFaceKeyStatus' : ActorMethod<[], string>,
  'getIsTradingPaused' : ActorMethod<[], boolean>,
  'getLatestHeadlines' : ActorMethod<[bigint], Array<NewsEvent>>,
  /**
   * / Returns the latest score snapshot committed by persistTick.
   * / PUBLIC query — no auth restriction. Used on frontend mount to bootstrap scores.
   */
  'getLatestScores' : ActorMethod<[], Array<[string, number]>>,
  /**
   * / Returns the most recent `limit` tick records, oldest first.
   * / PUBLIC query — no auth restriction. Used on frontend mount for hydration.
   */
  'getLatestTicks' : ActorMethod<[bigint], Array<TickRecord>>,
  'getNextRefreshTimeNs' : ActorMethod<[], bigint>,
  'getOracleStatus' : ActorMethod<[], string>,
  /**
   * / Returns all persisted AI-graded headlines, oldest first.
   * / PUBLIC — no auth restriction. Used on frontend mount to hydrate the Oracle Feed.
   */
  'getPersistedHeadlines' : ActorMethod<[], Array<ProcessedHeadline>>,
  'getRecentTransactions' : ActorMethod<[bigint], Array<Transaction>>,
  'getSentimentScores' : ActorMethod<[], Array<[string, number]>>,
  'getShortPositionCap' : ActorMethod<[], number>,
  'getSubsidyReserves' : ActorMethod<[], SubsidyReserveMap>,
  'getTotalAllocatedByIndex' : ActorMethod<[], Array<[string, number]>>,
  'getTotalPlatformTVL' : ActorMethod<[], number>,
  'getTotalSubsidyReserve' : ActorMethod<[], number>,
  'getTotalUsers' : ActorMethod<[], bigint>,
  'getTotalVolumeByIndex' : ActorMethod<[], Array<[string, number]>>,
  'getTransactionHistory' : ActorMethod<[], Array<Transaction>>,
  'getUserFullPosition' : ActorMethod<[string], FullPositionView>,
  /**
   * / Returns the most recent scores from the caller's personal history.
   */
  'getUserLatestScores' : ActorMethod<[], Array<[string, number]>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserShortPosition' : ActorMethod<[string], ShortPositionView>,
  /**
   * / Returns the caller's personal tick history, limited to the last N entries.
   */
  'getUserTickHistory' : ActorMethod<[bigint], Array<TickRecord>>,
  'getWalletBalance' : ActorMethod<[], number>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / Commits a single tick result to canister memory.
   * / Called fire-and-forget from OracleTickContext after each tick cycle.
   * / Capped at 720 entries (≈6 hours at 30-second ticks).
   */
  'persistTick' : ActorMethod<[TickRecord], undefined>,
  'redeemAll' : ActorMethod<[string], boolean>,
  'redeemFunds' : ActorMethod<[string, number], boolean>,
  'redeemShort' : ActorMethod<[string, number], RedeemShortResult>,
  /**
   * / Resets Reddit backoff state so the next heartbeat triggers an immediate retry.
   * / Use this after a canister top-up to avoid waiting up to 50 minutes for the
   * / backoff window to expire. Admin-gated — only canister admins may call this.
   */
  'resetRedditBackoff' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'schema' : ActorMethod<[], string>,
  /**
   * / Sets the Finnhub API key. Open during pre-deployment — any signed-in caller may set the key.
   */
  'setFinnhubKey' : ActorMethod<[string], undefined>,
  /**
   * / Sets the HuggingFace API key. Open during pre-deployment — any signed-in caller may set the key.
   */
  'setHuggingFaceKey' : ActorMethod<[string], undefined>,
  'setUserStatus' : ActorMethod<[string, AccountStatus], undefined>,
  /**
   * / Persists a fully-scored headline to canister memory.
   * / Called fire-and-forget from OracleTickContext after FinBERT scoring.
   * / No auth restriction.
   */
  'storeProcessedHeadline' : ActorMethod<[ProcessedHeadline], undefined>,
  'toggleTradingPaused' : ActorMethod<[], undefined>,
  'transform' : ActorMethod<[TransformArgs], HttpResponse>,
  'updateData' : ActorMethod<[], undefined>,
  'withdrawFunds' : ActorMethod<[number], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];