/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AllocateShortResult = IDL.Variant({
  'ok' : IDL.Record({ 'unitsOpened' : IDL.Float64 }),
  'err' : IDL.Text,
});
export const NewsEventCategory = IDL.Variant({
  'AI' : IDL.Null,
  'Mexico' : IDL.Null,
  'Washington' : IDL.Null,
  'Warriors' : IDL.Null,
});
export const NewsEvent = IDL.Record({
  'sentimentScore' : IDL.Float64,
  'headline' : IDL.Text,
  'category' : NewsEventCategory,
  'relatedIndex' : IDL.Opt(IDL.Text),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const Holding = IDL.Record({
  'allocationTimestamp' : IDL.Int,
  'accruedYield' : IDL.Float64,
  'units' : IDL.Float64,
  'assetName' : IDL.Text,
  'yieldStartTime' : IDL.Int,
});
export const AccountStatus = IDL.Variant({
  'Active' : IDL.Null,
  'Suspended' : IDL.Null,
});
export const AssetPrice = IDL.Record({
  'currentAllocated' : IDL.Float64,
  'name' : IDL.Text,
  'baseScore' : IDL.Float64,
  'redeemPrice' : IDL.Float64,
  'buyPrice' : IDL.Float64,
  'category' : IDL.Text,
  'maxAllocation' : IDL.Float64,
  'volatilityBuffer' : IDL.Float64,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'name' : IDL.Text,
});
export const CircuitBreakerStatus = IDL.Record({
  'velocity' : IDL.Float64,
  'breakerActive' : IDL.Bool,
});
export const TrendDirection = IDL.Variant({
  'up' : IDL.Null,
  'down' : IDL.Null,
});
export const TrendState = IDL.Record({
  'direction' : TrendDirection,
  'remainingDuration' : IDL.Nat,
  'stepSize' : IDL.Float64,
});
export const TickRecord = IDL.Record({
  'topHeadline' : IDL.Opt(IDL.Text),
  'tickIndex' : IDL.Nat,
  'scores' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
  'gsiValue' : IDL.Float64,
  'timestamp' : IDL.Int,
});
export const ProcessedHeadline = IDL.Record({
  'impact' : IDL.Float64,
  'sentimentLabel' : IDL.Text,
  'text' : IDL.Text,
  'targetIndex' : IDL.Text,
  'sourceTier' : IDL.Nat,
  'timestamp' : IDL.Int,
  'confidence' : IDL.Float64,
});
export const TransactionType = IDL.Variant({
  'buy' : IDL.Null,
  'sell' : IDL.Null,
  'deposit' : IDL.Null,
  'shortAllocate' : IDL.Null,
  'redeemAll' : IDL.Null,
  'withdrawal' : IDL.Null,
  'shortRedeem' : IDL.Null,
});
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'transactionType' : TransactionType,
  'username' : IDL.Text,
  'timestamp' : IDL.Int,
  'units' : IDL.Opt(IDL.Float64),
  'assetName' : IDL.Opt(IDL.Text),
  'amount' : IDL.Float64,
  'assetInvolved' : IDL.Opt(IDL.Text),
  'dollarAmount' : IDL.Opt(IDL.Float64),
});
export const SubsidyReserveEntry = IDL.Tuple(IDL.Text, IDL.Float64);
export const SubsidyReserveMap = IDL.Vec(SubsidyReserveEntry);
export const FullPositionView = IDL.Record({
  'shortUnits' : IDL.Float64,
  'longUnits' : IDL.Float64,
  'shortEntryScore' : IDL.Float64,
  'longEntryScore' : IDL.Float64,
  'shortMarkToMarketValue' : IDL.Float64,
  'longMarkToMarketValue' : IDL.Float64,
});
export const ShortPositionView = IDL.Record({
  'shortUnits' : IDL.Float64,
  'shortEntryScore' : IDL.Float64,
  'markToMarketValue' : IDL.Float64,
});
export const RedeemShortResult = IDL.Variant({
  'ok' : IDL.Record({ 'valueCredited' : IDL.Float64 }),
  'err' : IDL.Text,
});
export const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
export const HttpResponse = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(HttpHeader),
});
export const TransformArgs = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : HttpResponse,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'adjustUserBalance' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  'allocateFunds' : IDL.Func([IDL.Text, IDL.Float64], [IDL.Bool], []),
  'allocateShort' : IDL.Func(
      [IDL.Text, IDL.Float64],
      [AllocateShortResult],
      [],
    ),
  'analyzeSentiment' : IDL.Func([IDL.Text], [IDL.Text], []),
  'applyNewsEvent' : IDL.Func([NewsEvent], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'backfillVolume' : IDL.Func([], [], []),
  'classifyHeadline' : IDL.Func(
      [IDL.Text],
      [
        IDL.Record({
          'sentimentLabel' : IDL.Text,
          'source' : IDL.Text,
          'confidence' : IDL.Float64,
        }),
      ],
      [],
    ),
  'depositFunds' : IDL.Func([IDL.Float64], [], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'fetchACLUData' : IDL.Func([], [IDL.Text], []),
  'fetchBLSData' : IDL.Func([], [IDL.Text], []),
  'fetchCongressData' : IDL.Func([], [IDL.Text], []),
  'fetchCongressTraditionalData' : IDL.Func([], [IDL.Text], []),
  'fetchCourtListenerData' : IDL.Func([], [IDL.Text], []),
  'fetchEPAData' : IDL.Func([], [IDL.Text], []),
  'fetchFTCData' : IDL.Func([], [IDL.Text], []),
  'fetchFedData' : IDL.Func([], [IDL.Text], []),
  'fetchGDELTData' : IDL.Func([], [IDL.Text], []),
  'fetchGlobeNewswire' : IDL.Func([], [IDL.Text], []),
  'fetchNews' : IDL.Func([], [IDL.Text], []),
  'fetchOMDBDCData' : IDL.Func([], [IDL.Text], []),
  'fetchOMDBMarvelData' : IDL.Func([], [IDL.Text], []),
  'fetchRedditFeed' : IDL.Func([IDL.Text], [IDL.Text], []),
  'fetchReliefWebData' : IDL.Func([], [IDL.Text], []),
  'fetchSCOTUSData' : IDL.Func([], [IDL.Text], []),
  'fetchSECFilings' : IDL.Func([], [IDL.Text], []),
  'fetchTMDBData' : IDL.Func([], [IDL.Text], []),
  'fetchTMDBPopularData' : IDL.Func([], [IDL.Text], []),
  'fetchUSPTOData' : IDL.Func([], [IDL.Text], []),
  'fetchYouTubeData' : IDL.Func([], [IDL.Text], []),
  'getAllHoldings' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, Holding))],
      ['query'],
    ),
  'getAllUsers' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Tuple(
            IDL.Text,
            IDL.Float64,
            IDL.Float64,
            IDL.Float64,
            AccountStatus,
          )
        ),
      ],
      ['query'],
    ),
  'getAssetPrices' : IDL.Func([], [IDL.Vec(AssetPrice)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCircuitBreakerStatus' : IDL.Func(
      [IDL.Text],
      [CircuitBreakerStatus],
      ['query'],
    ),
  'getCurrentTrends' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, TrendState))],
      ['query'],
    ),
  'getCyclesBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getHoldings' : IDL.Func([IDL.Text], [IDL.Opt(Holding)], ['query']),
  'getHuggingFaceKeyStatus' : IDL.Func([], [IDL.Text], []),
  'getIsTradingPaused' : IDL.Func([], [IDL.Bool], ['query']),
  'getLatestHeadlines' : IDL.Func([IDL.Nat], [IDL.Vec(NewsEvent)], ['query']),
  'getLatestScores' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
      ['query'],
    ),
  'getLatestTicks' : IDL.Func([IDL.Nat], [IDL.Vec(TickRecord)], ['query']),
  'getNextRefreshTimeNs' : IDL.Func([], [IDL.Int], ['query']),
  'getOracleStatus' : IDL.Func([], [IDL.Text], ['query']),
  'getPersistedHeadlines' : IDL.Func(
      [],
      [IDL.Vec(ProcessedHeadline)],
      ['query'],
    ),
  'getRecentTransactions' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getSentimentScores' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
      ['query'],
    ),
  'getShortPositionCap' : IDL.Func([], [IDL.Float64], ['query']),
  'getSubsidyReserves' : IDL.Func([], [SubsidyReserveMap], ['query']),
  'getTotalAllocatedByIndex' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
      ['query'],
    ),
  'getTotalPlatformTVL' : IDL.Func([], [IDL.Float64], ['query']),
  'getTotalSubsidyReserve' : IDL.Func([], [IDL.Float64], ['query']),
  'getTotalUsers' : IDL.Func([], [IDL.Nat], ['query']),
  'getTotalVolumeByIndex' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
      ['query'],
    ),
  'getTransactionHistory' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getUserFullPosition' : IDL.Func([IDL.Text], [FullPositionView], ['query']),
  'getUserLatestScores' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserShortPosition' : IDL.Func([IDL.Text], [ShortPositionView], ['query']),
  'getUserTickHistory' : IDL.Func([IDL.Nat], [IDL.Vec(TickRecord)], ['query']),
  'getWalletBalance' : IDL.Func([], [IDL.Float64], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'persistTick' : IDL.Func([TickRecord], [], []),
  'redeemAll' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'redeemFunds' : IDL.Func([IDL.Text, IDL.Float64], [IDL.Bool], []),
  'redeemShort' : IDL.Func([IDL.Text, IDL.Float64], [RedeemShortResult], []),
  'resetRedditBackoff' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'setHuggingFaceKey' : IDL.Func([IDL.Text], [], []),
  'setUserStatus' : IDL.Func([IDL.Text, AccountStatus], [], []),
  'storeProcessedHeadline' : IDL.Func([ProcessedHeadline], [], []),
  'toggleTradingPaused' : IDL.Func([], [], []),
  'transform' : IDL.Func([TransformArgs], [HttpResponse], ['query']),
  'updateData' : IDL.Func([], [], []),
  'withdrawFunds' : IDL.Func([IDL.Float64], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AllocateShortResult = IDL.Variant({
    'ok' : IDL.Record({ 'unitsOpened' : IDL.Float64 }),
    'err' : IDL.Text,
  });
  const NewsEventCategory = IDL.Variant({
    'AI' : IDL.Null,
    'Mexico' : IDL.Null,
    'Washington' : IDL.Null,
    'Warriors' : IDL.Null,
  });
  const NewsEvent = IDL.Record({
    'sentimentScore' : IDL.Float64,
    'headline' : IDL.Text,
    'category' : NewsEventCategory,
    'relatedIndex' : IDL.Opt(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const Holding = IDL.Record({
    'allocationTimestamp' : IDL.Int,
    'accruedYield' : IDL.Float64,
    'units' : IDL.Float64,
    'assetName' : IDL.Text,
    'yieldStartTime' : IDL.Int,
  });
  const AccountStatus = IDL.Variant({
    'Active' : IDL.Null,
    'Suspended' : IDL.Null,
  });
  const AssetPrice = IDL.Record({
    'currentAllocated' : IDL.Float64,
    'name' : IDL.Text,
    'baseScore' : IDL.Float64,
    'redeemPrice' : IDL.Float64,
    'buyPrice' : IDL.Float64,
    'category' : IDL.Text,
    'maxAllocation' : IDL.Float64,
    'volatilityBuffer' : IDL.Float64,
  });
  const UserProfile = IDL.Record({ 'username' : IDL.Text, 'name' : IDL.Text });
  const CircuitBreakerStatus = IDL.Record({
    'velocity' : IDL.Float64,
    'breakerActive' : IDL.Bool,
  });
  const TrendDirection = IDL.Variant({ 'up' : IDL.Null, 'down' : IDL.Null });
  const TrendState = IDL.Record({
    'direction' : TrendDirection,
    'remainingDuration' : IDL.Nat,
    'stepSize' : IDL.Float64,
  });
  const TickRecord = IDL.Record({
    'topHeadline' : IDL.Opt(IDL.Text),
    'tickIndex' : IDL.Nat,
    'scores' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
    'gsiValue' : IDL.Float64,
    'timestamp' : IDL.Int,
  });
  const ProcessedHeadline = IDL.Record({
    'impact' : IDL.Float64,
    'sentimentLabel' : IDL.Text,
    'text' : IDL.Text,
    'targetIndex' : IDL.Text,
    'sourceTier' : IDL.Nat,
    'timestamp' : IDL.Int,
    'confidence' : IDL.Float64,
  });
  const TransactionType = IDL.Variant({
    'buy' : IDL.Null,
    'sell' : IDL.Null,
    'deposit' : IDL.Null,
    'shortAllocate' : IDL.Null,
    'redeemAll' : IDL.Null,
    'withdrawal' : IDL.Null,
    'shortRedeem' : IDL.Null,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'transactionType' : TransactionType,
    'username' : IDL.Text,
    'timestamp' : IDL.Int,
    'units' : IDL.Opt(IDL.Float64),
    'assetName' : IDL.Opt(IDL.Text),
    'amount' : IDL.Float64,
    'assetInvolved' : IDL.Opt(IDL.Text),
    'dollarAmount' : IDL.Opt(IDL.Float64),
  });
  const SubsidyReserveEntry = IDL.Tuple(IDL.Text, IDL.Float64);
  const SubsidyReserveMap = IDL.Vec(SubsidyReserveEntry);
  const FullPositionView = IDL.Record({
    'shortUnits' : IDL.Float64,
    'longUnits' : IDL.Float64,
    'shortEntryScore' : IDL.Float64,
    'longEntryScore' : IDL.Float64,
    'shortMarkToMarketValue' : IDL.Float64,
    'longMarkToMarketValue' : IDL.Float64,
  });
  const ShortPositionView = IDL.Record({
    'shortUnits' : IDL.Float64,
    'shortEntryScore' : IDL.Float64,
    'markToMarketValue' : IDL.Float64,
  });
  const RedeemShortResult = IDL.Variant({
    'ok' : IDL.Record({ 'valueCredited' : IDL.Float64 }),
    'err' : IDL.Text,
  });
  const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const HttpResponse = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HttpHeader),
  });
  const TransformArgs = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : HttpResponse,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'adjustUserBalance' : IDL.Func([IDL.Text, IDL.Float64], [], []),
    'allocateFunds' : IDL.Func([IDL.Text, IDL.Float64], [IDL.Bool], []),
    'allocateShort' : IDL.Func(
        [IDL.Text, IDL.Float64],
        [AllocateShortResult],
        [],
      ),
    'analyzeSentiment' : IDL.Func([IDL.Text], [IDL.Text], []),
    'applyNewsEvent' : IDL.Func([NewsEvent], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'backfillVolume' : IDL.Func([], [], []),
    'classifyHeadline' : IDL.Func(
        [IDL.Text],
        [
          IDL.Record({
            'sentimentLabel' : IDL.Text,
            'source' : IDL.Text,
            'confidence' : IDL.Float64,
          }),
        ],
        [],
      ),
    'depositFunds' : IDL.Func([IDL.Float64], [], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'fetchACLUData' : IDL.Func([], [IDL.Text], []),
    'fetchBLSData' : IDL.Func([], [IDL.Text], []),
    'fetchCongressData' : IDL.Func([], [IDL.Text], []),
    'fetchCongressTraditionalData' : IDL.Func([], [IDL.Text], []),
    'fetchCourtListenerData' : IDL.Func([], [IDL.Text], []),
    'fetchEPAData' : IDL.Func([], [IDL.Text], []),
    'fetchFTCData' : IDL.Func([], [IDL.Text], []),
    'fetchFedData' : IDL.Func([], [IDL.Text], []),
    'fetchGDELTData' : IDL.Func([], [IDL.Text], []),
    'fetchGlobeNewswire' : IDL.Func([], [IDL.Text], []),
    'fetchNews' : IDL.Func([], [IDL.Text], []),
    'fetchOMDBDCData' : IDL.Func([], [IDL.Text], []),
    'fetchOMDBMarvelData' : IDL.Func([], [IDL.Text], []),
    'fetchRedditFeed' : IDL.Func([IDL.Text], [IDL.Text], []),
    'fetchReliefWebData' : IDL.Func([], [IDL.Text], []),
    'fetchSCOTUSData' : IDL.Func([], [IDL.Text], []),
    'fetchSECFilings' : IDL.Func([], [IDL.Text], []),
    'fetchTMDBData' : IDL.Func([], [IDL.Text], []),
    'fetchTMDBPopularData' : IDL.Func([], [IDL.Text], []),
    'fetchUSPTOData' : IDL.Func([], [IDL.Text], []),
    'fetchYouTubeData' : IDL.Func([], [IDL.Text], []),
    'getAllHoldings' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, Holding))],
        ['query'],
      ),
    'getAllUsers' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Tuple(
              IDL.Text,
              IDL.Float64,
              IDL.Float64,
              IDL.Float64,
              AccountStatus,
            )
          ),
        ],
        ['query'],
      ),
    'getAssetPrices' : IDL.Func([], [IDL.Vec(AssetPrice)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCircuitBreakerStatus' : IDL.Func(
        [IDL.Text],
        [CircuitBreakerStatus],
        ['query'],
      ),
    'getCurrentTrends' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, TrendState))],
        ['query'],
      ),
    'getCyclesBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getHoldings' : IDL.Func([IDL.Text], [IDL.Opt(Holding)], ['query']),
    'getHuggingFaceKeyStatus' : IDL.Func([], [IDL.Text], []),
    'getIsTradingPaused' : IDL.Func([], [IDL.Bool], ['query']),
    'getLatestHeadlines' : IDL.Func([IDL.Nat], [IDL.Vec(NewsEvent)], ['query']),
    'getLatestScores' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
        ['query'],
      ),
    'getLatestTicks' : IDL.Func([IDL.Nat], [IDL.Vec(TickRecord)], ['query']),
    'getNextRefreshTimeNs' : IDL.Func([], [IDL.Int], ['query']),
    'getOracleStatus' : IDL.Func([], [IDL.Text], ['query']),
    'getPersistedHeadlines' : IDL.Func(
        [],
        [IDL.Vec(ProcessedHeadline)],
        ['query'],
      ),
    'getRecentTransactions' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getSentimentScores' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
        ['query'],
      ),
    'getShortPositionCap' : IDL.Func([], [IDL.Float64], ['query']),
    'getSubsidyReserves' : IDL.Func([], [SubsidyReserveMap], ['query']),
    'getTotalAllocatedByIndex' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
        ['query'],
      ),
    'getTotalPlatformTVL' : IDL.Func([], [IDL.Float64], ['query']),
    'getTotalSubsidyReserve' : IDL.Func([], [IDL.Float64], ['query']),
    'getTotalUsers' : IDL.Func([], [IDL.Nat], ['query']),
    'getTotalVolumeByIndex' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
        ['query'],
      ),
    'getTransactionHistory' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getUserFullPosition' : IDL.Func([IDL.Text], [FullPositionView], ['query']),
    'getUserLatestScores' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserShortPosition' : IDL.Func(
        [IDL.Text],
        [ShortPositionView],
        ['query'],
      ),
    'getUserTickHistory' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(TickRecord)],
        ['query'],
      ),
    'getWalletBalance' : IDL.Func([], [IDL.Float64], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'persistTick' : IDL.Func([TickRecord], [], []),
    'redeemAll' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'redeemFunds' : IDL.Func([IDL.Text, IDL.Float64], [IDL.Bool], []),
    'redeemShort' : IDL.Func([IDL.Text, IDL.Float64], [RedeemShortResult], []),
    'resetRedditBackoff' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'setHuggingFaceKey' : IDL.Func([IDL.Text], [], []),
    'setUserStatus' : IDL.Func([IDL.Text, AccountStatus], [], []),
    'storeProcessedHeadline' : IDL.Func([ProcessedHeadline], [], []),
    'toggleTradingPaused' : IDL.Func([], [], []),
    'transform' : IDL.Func([TransformArgs], [HttpResponse], ['query']),
    'updateData' : IDL.Func([], [], []),
    'withdrawFunds' : IDL.Func([IDL.Float64], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };