/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export interface CircuitBreakerStatus {
    velocity: number;
    breakerActive: boolean;
}
export interface AssetPrice {
    currentAllocated: number;
    name: string;
    baseScore: number;
    redeemPrice: number;
    buyPrice: number;
    category: string;
    maxAllocation: number;
    volatilityBuffer: number;
}
export type SubsidyReserveMap = Array<SubsidyReserveEntry>;
export interface ProcessedHeadline {
    impact: number;
    sentimentLabel: string;
    text: string;
    targetIndex: string;
    sourceTier: bigint;
    timestamp: bigint;
    confidence: number;
}
export interface NewsEvent {
    sentimentScore: number;
    headline: string;
    category: NewsEventCategory;
    relatedIndex?: string;
}
export interface TrendState {
    direction: TrendDirection;
    remainingDuration: bigint;
    stepSize: number;
}
export interface HttpHeader {
    value: string;
    name: string;
}
export interface Transaction {
    id: bigint;
    transactionType: TransactionType;
    username: string;
    timestamp: bigint;
    units?: number;
    assetName?: string;
    amount: number;
    assetInvolved?: string;
    dollarAmount?: number;
}
export type AllocateShortResult = {
    __kind__: "ok";
    ok: {
        unitsOpened: number;
    };
} | {
    __kind__: "err";
    err: string;
};
export interface TickRecord {
    topHeadline?: string;
    tickIndex: bigint;
    scores: Array<[string, number]>;
    gsiValue: number;
    timestamp: bigint;
}
export interface Result {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export interface Holding {
    allocationTimestamp: bigint;
    accruedYield: number;
    units: number;
    assetName: string;
    yieldStartTime: bigint;
}
export interface HttpResponse {
    status: bigint;
    body: Uint8Array;
    headers: Array<HttpHeader>;
}
export interface FullPositionView {
    shortUnits: number;
    longUnits: number;
    shortEntryScore: number;
    longEntryScore: number;
    shortMarkToMarketValue: number;
    longMarkToMarketValue: number;
}
export interface Cell {
    value: Value;
    name: string;
}
export interface ShortPositionView {
    shortUnits: number;
    shortEntryScore: number;
    markToMarketValue: number;
}
export type SubsidyReserveEntry = [string, number];
export type RedeemShortResult = {
    __kind__: "ok";
    ok: {
        valueCredited: number;
    };
} | {
    __kind__: "err";
    err: string;
};
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export interface UserProfile {
    username: string;
    name: string;
}
export interface TransformArgs {
    context: Uint8Array;
    response: HttpResponse;
}
export enum AccountStatus {
    Active = "Active",
    Suspended = "Suspended"
}
export enum NewsEventCategory {
    AI = "AI",
    Mexico = "Mexico",
    Washington = "Washington",
    Warriors = "Warriors"
}
export enum TransactionType {
    buy = "buy",
    sell = "sell",
    deposit = "deposit",
    shortAllocate = "shortAllocate",
    redeemAll = "redeemAll",
    withdrawal = "withdrawal",
    shortRedeem = "shortRedeem"
}
export enum TrendDirection {
    up = "up",
    down = "down"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    adjustUserBalance(_userId: string, amount: number): Promise<void>;
    allocateFunds(assetName: string, allocationAmount: number): Promise<boolean>;
    allocateShort(assetName: string, allocationAmount: number): Promise<AllocateShortResult>;
    /**
     * / Legacy function retained for backward compatibility.
     * / New callers should use classifyHeadline() instead.
     */
    analyzeSentiment(text: string): Promise<string>;
    applyNewsEvent(event: NewsEvent): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    backfillVolume(): Promise<void>;
    /**
     * / Public update function — frontend calls this to classify a headline.
     * / HTTP outcalls require update calls (not query).
     * / Returns neutral_fallback if key is not set or on any error.
     * / NOTE: field is "sentimentLabel" not "label" — "label" is a reserved keyword in Motoko.
     */
    classifyHeadline(headline: string): Promise<{
        sentimentLabel: string;
        source: string;
        confidence: number;
    }>;
    depositFunds(amount: number): Promise<void>;
    execute(qJson: string): Promise<Result>;
    fetchACLUData(): Promise<string>;
    fetchBLSData(): Promise<string>;
    fetchCongressData(): Promise<string>;
    fetchCongressTraditionalData(): Promise<string>;
    fetchCourtListenerData(): Promise<string>;
    fetchEPAData(): Promise<string>;
    fetchFTCData(): Promise<string>;
    fetchFedData(): Promise<string>;
    fetchGDELTData(): Promise<string>;
    fetchGlobeNewswire(): Promise<string>;
    fetchNews(): Promise<string>;
    fetchOMDBDCData(): Promise<string>;
    fetchOMDBMarvelData(): Promise<string>;
    fetchRedditFeed(subreddit: string): Promise<string>;
    fetchReliefWebData(): Promise<string>;
    fetchSCOTUSData(): Promise<string>;
    fetchSECFilings(): Promise<string>;
    fetchTMDBData(): Promise<string>;
    fetchTMDBPopularData(): Promise<string>;
    fetchUSPTOData(): Promise<string>;
    fetchYouTubeData(): Promise<string>;
    getAllHoldings(): Promise<Array<[string, Holding]>>;
    getAllUsers(): Promise<Array<[string, number, number, number, AccountStatus]>>;
    getAssetPrices(): Promise<Array<AssetPrice>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCircuitBreakerStatus(assetName: string): Promise<CircuitBreakerStatus>;
    getCurrentTrends(): Promise<Array<[string, TrendState]>>;
    /**
     * / Returns the current cycles balance of this canister.
     * / PUBLIC — no auth required. Use for monitoring without controller access:
     * /   dfx canister call noek7-3yaaa-aaaaj-qn6ea-cai getCyclesBalance --network ic
     */
    getCyclesBalance(): Promise<bigint>;
    /**
     * / Returns Finnhub key status without exposing the value. Open during pre-deployment — any signed-in caller may check the key.
     */
    getFinnhubKeyStatus(): Promise<string>;
    getHoldings(assetName: string): Promise<Holding | null>;
    /**
     * / Returns key status without exposing the value. Open during pre-deployment — any signed-in caller may check the key.
     */
    getHuggingFaceKeyStatus(): Promise<string>;
    getIsTradingPaused(): Promise<boolean>;
    getLatestHeadlines(limit: bigint): Promise<Array<NewsEvent>>;
    /**
     * / Returns the latest score snapshot committed by persistTick.
     * / PUBLIC query — no auth restriction. Used on frontend mount to bootstrap scores.
     */
    getLatestScores(): Promise<Array<[string, number]>>;
    /**
     * / Returns the most recent `limit` tick records, oldest first.
     * / PUBLIC query — no auth restriction. Used on frontend mount for hydration.
     */
    getLatestTicks(limit: bigint): Promise<Array<TickRecord>>;
    getNextRefreshTimeNs(): Promise<bigint>;
    getOracleStatus(): Promise<string>;
    /**
     * / Returns all persisted AI-graded headlines, oldest first.
     * / PUBLIC — no auth restriction. Used on frontend mount to hydrate the Oracle Feed.
     */
    getPersistedHeadlines(): Promise<Array<ProcessedHeadline>>;
    getRecentTransactions(limit: bigint): Promise<Array<Transaction>>;
    getSentimentScores(): Promise<Array<[string, number]>>;
    getShortPositionCap(): Promise<number>;
    getSubsidyReserves(): Promise<SubsidyReserveMap>;
    getTotalAllocatedByIndex(): Promise<Array<[string, number]>>;
    getTotalPlatformTVL(): Promise<number>;
    getTotalSubsidyReserve(): Promise<number>;
    getTotalUsers(): Promise<bigint>;
    getTotalVolumeByIndex(): Promise<Array<[string, number]>>;
    getTransactionHistory(): Promise<Array<Transaction>>;
    getUserFullPosition(assetName: string): Promise<FullPositionView>;
    /**
     * / Returns the most recent scores from the caller's personal history.
     */
    getUserLatestScores(): Promise<Array<[string, number]>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserShortPosition(assetName: string): Promise<ShortPositionView>;
    /**
     * / Returns the caller's personal tick history, limited to the last N entries.
     */
    getUserTickHistory(limit: bigint): Promise<Array<TickRecord>>;
    getWalletBalance(): Promise<number>;
    isCallerAdmin(): Promise<boolean>;
    /**
     * / Commits a single tick result to canister memory.
     * / Called fire-and-forget from OracleTickContext after each tick cycle.
     * / Capped at 720 entries (≈6 hours at 30-second ticks).
     */
    persistTick(record: TickRecord): Promise<void>;
    redeemAll(assetName: string): Promise<boolean>;
    redeemFunds(assetName: string, unitsToSell: number): Promise<boolean>;
    redeemShort(assetName: string, unitsToRedeem: number): Promise<RedeemShortResult>;
    /**
     * / Resets Reddit backoff state so the next heartbeat triggers an immediate retry.
     * / Use this after a canister top-up to avoid waiting up to 50 minutes for the
     * / backoff window to expire. Admin-gated — only canister admins may call this.
     */
    resetRedditBackoff(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    schema(): Promise<string>;
    /**
     * / Sets the Finnhub API key. Open during pre-deployment — any signed-in caller may set the key.
     */
    setFinnhubKey(key: string): Promise<void>;
    /**
     * / Sets the HuggingFace API key. Open during pre-deployment — any signed-in caller may set the key.
     */
    setHuggingFaceKey(key: string): Promise<void>;
    setUserStatus(username: string, status: AccountStatus): Promise<void>;
    /**
     * / Persists a fully-scored headline to canister memory.
     * / Called fire-and-forget from OracleTickContext after FinBERT scoring.
     * / No auth restriction.
     */
    storeProcessedHeadline(h: ProcessedHeadline): Promise<void>;
    toggleTradingPaused(): Promise<void>;
    transform(args: TransformArgs): Promise<HttpResponse>;
    updateData(): Promise<void>;
    withdrawFunds(amount: number): Promise<boolean>;
}
import type { AccountStatus as _AccountStatus, AllocateShortResult as _AllocateShortResult, Cell as _Cell, Holding as _Holding, NewsEvent as _NewsEvent, NewsEventCategory as _NewsEventCategory, RedeemShortResult as _RedeemShortResult, Result as _Result, TickRecord as _TickRecord, Transaction as _Transaction, TransactionType as _TransactionType, TrendDirection as _TrendDirection, TrendState as _TrendState, UserProfile as _UserProfile, UserRole as _UserRole, Value as _Value } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async adjustUserBalance(arg0: string, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adjustUserBalance(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adjustUserBalance(arg0, arg1);
            return result;
        }
    }
    async allocateFunds(arg0: string, arg1: number): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.allocateFunds(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.allocateFunds(arg0, arg1);
            return result;
        }
    }
    async allocateShort(arg0: string, arg1: number): Promise<AllocateShortResult> {
        if (this.processError) {
            try {
                const result = await this.actor.allocateShort(arg0, arg1);
                return from_candid_AllocateShortResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.allocateShort(arg0, arg1);
            return from_candid_AllocateShortResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async analyzeSentiment(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.analyzeSentiment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.analyzeSentiment(arg0);
            return result;
        }
    }
    async applyNewsEvent(arg0: NewsEvent): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.applyNewsEvent(to_candid_NewsEvent_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.applyNewsEvent(to_candid_NewsEvent_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n7(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n7(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async backfillVolume(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.backfillVolume();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.backfillVolume();
            return result;
        }
    }
    async classifyHeadline(arg0: string): Promise<{
        sentimentLabel: string;
        source: string;
        confidence: number;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.classifyHeadline(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.classifyHeadline(arg0);
            return result;
        }
    }
    async depositFunds(arg0: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.depositFunds(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.depositFunds(arg0);
            return result;
        }
    }
    async execute(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async fetchACLUData(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchACLUData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchACLUData();
            return result;
        }
    }
    async fetchBLSData(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchBLSData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchBLSData();
            return result;
        }
    }
    async fetchCongressData(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchCongressData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchCongressData();
            return result;
        }
    }
    async fetchCongressTraditionalData(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchCongressTraditionalData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchCongressTraditionalData();
            return result;
        }
    }
    async fetchCourtListenerData(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchCourtListenerData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchCourtListenerData();
            return result;
        }
    }
    async fetchEPAData(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchEPAData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchEPAData();
            return result;
        }
    }
    async fetchFTCData(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchFTCData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchFTCData();
            return result;
        }
    }
    async fetchFedData(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchFedData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchFedData();
            return result;
        }
    }
    async fetchGDELTData(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchGDELTData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchGDELTData();
            return result;
        }
    }
    async fetchGlobeNewswire(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchGlobeNewswire();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchGlobeNewswire();
            return result;
        }
    }
    async fetchNews(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchNews();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchNews();
            return result;
        }
    }
    async fetchOMDBDCData(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchOMDBDCData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchOMDBDCData();
            return result;
        }
    }
    async fetchOMDBMarvelData(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchOMDBMarvelData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchOMDBMarvelData();
            return result;
        }
    }
    async fetchRedditFeed(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchRedditFeed(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchRedditFeed(arg0);
            return result;
        }
    }
    async fetchReliefWebData(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchReliefWebData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchReliefWebData();
            return result;
        }
    }
    async fetchSCOTUSData(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchSCOTUSData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchSCOTUSData();
            return result;
        }
    }
    async fetchSECFilings(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchSECFilings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchSECFilings();
            return result;
        }
    }
    async fetchTMDBData(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchTMDBData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchTMDBData();
            return result;
        }
    }
    async fetchTMDBPopularData(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchTMDBPopularData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchTMDBPopularData();
            return result;
        }
    }
    async fetchUSPTOData(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchUSPTOData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchUSPTOData();
            return result;
        }
    }
    async fetchYouTubeData(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchYouTubeData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchYouTubeData();
            return result;
        }
    }
    async getAllHoldings(): Promise<Array<[string, Holding]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllHoldings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllHoldings();
            return result;
        }
    }
    async getAllUsers(): Promise<Array<[string, number, number, number, AccountStatus]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAssetPrices(): Promise<Array<AssetPrice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAssetPrices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAssetPrices();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCircuitBreakerStatus(arg0: string): Promise<CircuitBreakerStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getCircuitBreakerStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCircuitBreakerStatus(arg0);
            return result;
        }
    }
    async getCurrentTrends(): Promise<Array<[string, TrendState]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentTrends();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentTrends();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCyclesBalance(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getCyclesBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCyclesBalance();
            return result;
        }
    }
    async getFinnhubKeyStatus(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getFinnhubKeyStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFinnhubKeyStatus();
            return result;
        }
    }
    async getHoldings(arg0: string): Promise<Holding | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getHoldings(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHoldings(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHuggingFaceKeyStatus(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getHuggingFaceKeyStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHuggingFaceKeyStatus();
            return result;
        }
    }
    async getIsTradingPaused(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.getIsTradingPaused();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIsTradingPaused();
            return result;
        }
    }
    async getLatestHeadlines(arg0: bigint): Promise<Array<NewsEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLatestHeadlines(arg0);
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLatestHeadlines(arg0);
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLatestScores(): Promise<Array<[string, number]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLatestScores();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLatestScores();
            return result;
        }
    }
    async getLatestTicks(arg0: bigint): Promise<Array<TickRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLatestTicks(arg0);
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLatestTicks(arg0);
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNextRefreshTimeNs(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getNextRefreshTimeNs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNextRefreshTimeNs();
            return result;
        }
    }
    async getOracleStatus(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getOracleStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOracleStatus();
            return result;
        }
    }
    async getPersistedHeadlines(): Promise<Array<ProcessedHeadline>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPersistedHeadlines();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPersistedHeadlines();
            return result;
        }
    }
    async getRecentTransactions(arg0: bigint): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecentTransactions(arg0);
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecentTransactions(arg0);
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSentimentScores(): Promise<Array<[string, number]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSentimentScores();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSentimentScores();
            return result;
        }
    }
    async getShortPositionCap(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getShortPositionCap();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShortPositionCap();
            return result;
        }
    }
    async getSubsidyReserves(): Promise<SubsidyReserveMap> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubsidyReserves();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubsidyReserves();
            return result;
        }
    }
    async getTotalAllocatedByIndex(): Promise<Array<[string, number]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalAllocatedByIndex();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalAllocatedByIndex();
            return result;
        }
    }
    async getTotalPlatformTVL(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalPlatformTVL();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalPlatformTVL();
            return result;
        }
    }
    async getTotalSubsidyReserve(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalSubsidyReserve();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalSubsidyReserve();
            return result;
        }
    }
    async getTotalUsers(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalUsers();
            return result;
        }
    }
    async getTotalVolumeByIndex(): Promise<Array<[string, number]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalVolumeByIndex();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalVolumeByIndex();
            return result;
        }
    }
    async getTransactionHistory(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactionHistory();
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactionHistory();
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserFullPosition(arg0: string): Promise<FullPositionView> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserFullPosition(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserFullPosition(arg0);
            return result;
        }
    }
    async getUserLatestScores(): Promise<Array<[string, number]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserLatestScores();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserLatestScores();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserShortPosition(arg0: string): Promise<ShortPositionView> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserShortPosition(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserShortPosition(arg0);
            return result;
        }
    }
    async getUserTickHistory(arg0: bigint): Promise<Array<TickRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserTickHistory(arg0);
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserTickHistory(arg0);
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWalletBalance(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getWalletBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWalletBalance();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async persistTick(arg0: TickRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.persistTick(to_candid_TickRecord_n46(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.persistTick(to_candid_TickRecord_n46(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async redeemAll(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.redeemAll(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.redeemAll(arg0);
            return result;
        }
    }
    async redeemFunds(arg0: string, arg1: number): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.redeemFunds(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.redeemFunds(arg0, arg1);
            return result;
        }
    }
    async redeemShort(arg0: string, arg1: number): Promise<RedeemShortResult> {
        if (this.processError) {
            try {
                const result = await this.actor.redeemShort(arg0, arg1);
                return from_candid_RedeemShortResult_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.redeemShort(arg0, arg1);
            return from_candid_RedeemShortResult_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async resetRedditBackoff(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetRedditBackoff();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetRedditBackoff();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
    async setFinnhubKey(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setFinnhubKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setFinnhubKey(arg0);
            return result;
        }
    }
    async setHuggingFaceKey(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setHuggingFaceKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setHuggingFaceKey(arg0);
            return result;
        }
    }
    async setUserStatus(arg0: string, arg1: AccountStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setUserStatus(arg0, to_candid_AccountStatus_n50(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUserStatus(arg0, to_candid_AccountStatus_n50(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async storeProcessedHeadline(arg0: ProcessedHeadline): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.storeProcessedHeadline(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storeProcessedHeadline(arg0);
            return result;
        }
    }
    async toggleTradingPaused(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleTradingPaused();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleTradingPaused();
            return result;
        }
    }
    async transform(arg0: TransformArgs): Promise<HttpResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateData();
            return result;
        }
    }
    async withdrawFunds(arg0: number): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.withdrawFunds(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.withdrawFunds(arg0);
            return result;
        }
    }
}
function from_candid_AccountStatus_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AccountStatus): AccountStatus {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_AllocateShortResult_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AllocateShortResult): AllocateShortResult {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Cell_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_NewsEventCategory_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NewsEventCategory): NewsEventCategory {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_NewsEvent_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NewsEvent): NewsEvent {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_RedeemShortResult_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RedeemShortResult): RedeemShortResult {
    return from_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_TickRecord_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TickRecord): TickRecord {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionType_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionType): TransactionType {
    return from_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_TrendDirection_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TrendDirection): TrendDirection {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_TrendState_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TrendState): TrendState {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Value_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Holding]): Holding | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n11(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n15(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    direction: _TrendDirection;
    remainingDuration: bigint;
    stepSize: number;
}): {
    direction: TrendDirection;
    remainingDuration: bigint;
    stepSize: number;
} {
    return {
        direction: from_candid_TrendDirection_n28(_uploadFile, _downloadFile, value.direction),
        remainingDuration: value.remainingDuration,
        stepSize: value.stepSize
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sentimentScore: number;
    headline: string;
    category: _NewsEventCategory;
    relatedIndex: [] | [string];
}): {
    sentimentScore: number;
    headline: string;
    category: NewsEventCategory;
    relatedIndex?: string;
} {
    return {
        sentimentScore: value.sentimentScore,
        headline: value.headline,
        category: from_candid_NewsEventCategory_n34(_uploadFile, _downloadFile, value.category),
        relatedIndex: record_opt_to_undefined(from_candid_opt_n36(_uploadFile, _downloadFile, value.relatedIndex))
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    topHeadline: [] | [string];
    tickIndex: bigint;
    scores: Array<[string, number]>;
    gsiValue: number;
    timestamp: bigint;
}): {
    topHeadline?: string;
    tickIndex: bigint;
    scores: Array<[string, number]>;
    gsiValue: number;
    timestamp: bigint;
} {
    return {
        topHeadline: record_opt_to_undefined(from_candid_opt_n36(_uploadFile, _downloadFile, value.topHeadline)),
        tickIndex: value.tickIndex,
        scores: value.scores,
        gsiValue: value.gsiValue,
        timestamp: value.timestamp
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    transactionType: _TransactionType;
    username: string;
    timestamp: bigint;
    units: [] | [number];
    assetName: [] | [string];
    amount: number;
    assetInvolved: [] | [string];
    dollarAmount: [] | [number];
}): {
    id: bigint;
    transactionType: TransactionType;
    username: string;
    timestamp: bigint;
    units?: number;
    assetName?: string;
    amount: number;
    assetInvolved?: string;
    dollarAmount?: number;
} {
    return {
        id: value.id,
        transactionType: from_candid_TransactionType_n43(_uploadFile, _downloadFile, value.transactionType),
        username: value.username,
        timestamp: value.timestamp,
        units: record_opt_to_undefined(from_candid_opt_n45(_uploadFile, _downloadFile, value.units)),
        assetName: record_opt_to_undefined(from_candid_opt_n36(_uploadFile, _downloadFile, value.assetName)),
        amount: value.amount,
        assetInvolved: record_opt_to_undefined(from_candid_opt_n36(_uploadFile, _downloadFile, value.assetInvolved)),
        dollarAmount: record_opt_to_undefined(from_candid_opt_n45(_uploadFile, _downloadFile, value.dollarAmount))
    };
}
function from_candid_tuple_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, number, number, number, _AccountStatus]): [string, number, number, number, AccountStatus] {
    return [
        value[0],
        value[1],
        value[2],
        value[3],
        from_candid_AccountStatus_n19(_uploadFile, _downloadFile, value[4])
    ];
}
function from_candid_tuple_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, _TrendState]): [string, TrendState] {
    return [
        value[0],
        from_candid_TrendState_n26(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: {
        unitsOpened: number;
    };
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: {
        unitsOpened: number;
    };
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Active: null;
} | {
    Suspended: null;
}): AccountStatus {
    return "Active" in value ? AccountStatus.Active : "Suspended" in value ? AccountStatus.Suspended : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    up: null;
} | {
    down: null;
}): TrendDirection {
    return "up" in value ? TrendDirection.up : "down" in value ? TrendDirection.down : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    AI: null;
} | {
    Mexico: null;
} | {
    Washington: null;
} | {
    Warriors: null;
}): NewsEventCategory {
    return "AI" in value ? NewsEventCategory.AI : "Mexico" in value ? NewsEventCategory.Mexico : "Washington" in value ? NewsEventCategory.Washington : "Warriors" in value ? NewsEventCategory.Warriors : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    buy: null;
} | {
    sell: null;
} | {
    deposit: null;
} | {
    shortAllocate: null;
} | {
    redeemAll: null;
} | {
    withdrawal: null;
} | {
    shortRedeem: null;
}): TransactionType {
    return "buy" in value ? TransactionType.buy : "sell" in value ? TransactionType.sell : "deposit" in value ? TransactionType.deposit : "shortAllocate" in value ? TransactionType.shortAllocate : "redeemAll" in value ? TransactionType.redeemAll : "withdrawal" in value ? TransactionType.withdrawal : "shortRedeem" in value ? TransactionType.shortRedeem : value;
}
function from_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: {
        valueCredited: number;
    };
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: {
        valueCredited: number;
    };
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, number, number, number, _AccountStatus]>): Array<[string, number, number, number, AccountStatus]> {
    return value.map((x)=>from_candid_tuple_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, _TrendState]>): Array<[string, TrendState]> {
    return value.map((x)=>from_candid_tuple_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_NewsEvent>): Array<NewsEvent> {
    return value.map((x)=>from_candid_NewsEvent_n32(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TickRecord>): Array<TickRecord> {
    return value.map((x)=>from_candid_TickRecord_n38(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n41(_uploadFile, _downloadFile, x));
}
function to_candid_AccountStatus_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AccountStatus): _AccountStatus {
    return to_candid_variant_n51(_uploadFile, _downloadFile, value);
}
function to_candid_NewsEventCategory_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NewsEventCategory): _NewsEventCategory {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_NewsEvent_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NewsEvent): _NewsEvent {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_TickRecord_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TickRecord): _TickRecord {
    return to_candid_record_n47(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sentimentScore: number;
    headline: string;
    category: NewsEventCategory;
    relatedIndex?: string;
}): {
    sentimentScore: number;
    headline: string;
    category: _NewsEventCategory;
    relatedIndex: [] | [string];
} {
    return {
        sentimentScore: value.sentimentScore,
        headline: value.headline,
        category: to_candid_NewsEventCategory_n5(_uploadFile, _downloadFile, value.category),
        relatedIndex: value.relatedIndex ? candid_some(value.relatedIndex) : candid_none()
    };
}
function to_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    topHeadline?: string;
    tickIndex: bigint;
    scores: Array<[string, number]>;
    gsiValue: number;
    timestamp: bigint;
}): {
    topHeadline: [] | [string];
    tickIndex: bigint;
    scores: Array<[string, number]>;
    gsiValue: number;
    timestamp: bigint;
} {
    return {
        topHeadline: value.topHeadline ? candid_some(value.topHeadline) : candid_none(),
        tickIndex: value.tickIndex,
        scores: value.scores,
        gsiValue: value.gsiValue,
        timestamp: value.timestamp
    };
}
function to_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AccountStatus): {
    Active: null;
} | {
    Suspended: null;
} {
    return value == AccountStatus.Active ? {
        Active: null
    } : value == AccountStatus.Suspended ? {
        Suspended: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NewsEventCategory): {
    AI: null;
} | {
    Mexico: null;
} | {
    Washington: null;
} | {
    Warriors: null;
} {
    return value == NewsEventCategory.AI ? {
        AI: null
    } : value == NewsEventCategory.Mexico ? {
        Mexico: null
    } : value == NewsEventCategory.Washington ? {
        Washington: null
    } : value == NewsEventCategory.Warriors ? {
        Warriors: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
